// Code generated by protoc-gen-go. DO NOT EDIT.
// source: Student.proto

package main

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gender int32

const (
	Gender_Female Gender = 0
	Gender_Male   Gender = 1
)

var Gender_name = map[int32]string{
	0: "Female",
	1: "Male",
}

var Gender_value = map[string]int32{
	"Female": 0,
	"Male":   1,
}

func (x Gender) String() string {
	return proto.EnumName(Gender_name, int32(x))
}

func (Gender) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{0}
}

type Parents struct {
	Dad                  string   `protobuf:"bytes,1,opt,name=dad,proto3" json:"dad,omitempty"`
	Mom                  string   `protobuf:"bytes,2,opt,name=mom,proto3" json:"mom,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Parents) Reset()         { *m = Parents{} }
func (m *Parents) String() string { return proto.CompactTextString(m) }
func (*Parents) ProtoMessage()    {}
func (*Parents) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{0}
}

func (m *Parents) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Parents.Unmarshal(m, b)
}
func (m *Parents) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Parents.Marshal(b, m, deterministic)
}
func (m *Parents) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Parents.Merge(m, src)
}
func (m *Parents) XXX_Size() int {
	return xxx_messageInfo_Parents.Size(m)
}
func (m *Parents) XXX_DiscardUnknown() {
	xxx_messageInfo_Parents.DiscardUnknown(m)
}

var xxx_messageInfo_Parents proto.InternalMessageInfo

func (m *Parents) GetDad() string {
	if m != nil {
		return m.Dad
	}
	return ""
}

func (m *Parents) GetMom() string {
	if m != nil {
		return m.Mom
	}
	return ""
}

type Student struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32    `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Parents              *Parents `protobuf:"bytes,3,opt,name=parents,proto3" json:"parents,omitempty"`
	Gender               Gender   `protobuf:"varint,4,opt,name=gender,proto3,enum=main.Gender" json:"gender,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Student) Reset()         { *m = Student{} }
func (m *Student) String() string { return proto.CompactTextString(m) }
func (*Student) ProtoMessage()    {}
func (*Student) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{1}
}

func (m *Student) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Student.Unmarshal(m, b)
}
func (m *Student) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Student.Marshal(b, m, deterministic)
}
func (m *Student) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Student.Merge(m, src)
}
func (m *Student) XXX_Size() int {
	return xxx_messageInfo_Student.Size(m)
}
func (m *Student) XXX_DiscardUnknown() {
	xxx_messageInfo_Student.DiscardUnknown(m)
}

var xxx_messageInfo_Student proto.InternalMessageInfo

func (m *Student) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Student) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *Student) GetParents() *Parents {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Student) GetGender() Gender {
	if m != nil {
		return m.Gender
	}
	return Gender_Female
}

type Students struct {
	StudentEntry         [][]byte `protobuf:"bytes,1,rep,name=StudentEntry,proto3" json:"StudentEntry,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Students) Reset()         { *m = Students{} }
func (m *Students) String() string { return proto.CompactTextString(m) }
func (*Students) ProtoMessage()    {}
func (*Students) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4c3db915bb432d, []int{2}
}

func (m *Students) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Students.Unmarshal(m, b)
}
func (m *Students) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Students.Marshal(b, m, deterministic)
}
func (m *Students) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Students.Merge(m, src)
}
func (m *Students) XXX_Size() int {
	return xxx_messageInfo_Students.Size(m)
}
func (m *Students) XXX_DiscardUnknown() {
	xxx_messageInfo_Students.DiscardUnknown(m)
}

var xxx_messageInfo_Students proto.InternalMessageInfo

func (m *Students) GetStudentEntry() [][]byte {
	if m != nil {
		return m.StudentEntry
	}
	return nil
}

func init() {
	proto.RegisterEnum("main.Gender", Gender_name, Gender_value)
	proto.RegisterType((*Parents)(nil), "main.Parents")
	proto.RegisterType((*Student)(nil), "main.Student")
	proto.RegisterType((*Students)(nil), "main.Students")
}

func init() { proto.RegisterFile("Student.proto", fileDescriptor_2f4c3db915bb432d) }

var fileDescriptor_2f4c3db915bb432d = []byte{
	// 214 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0xbf, 0x4a, 0x04, 0x31,
	0x10, 0xc6, 0x8d, 0xbb, 0xee, 0x9e, 0xe3, 0x9e, 0x1c, 0x53, 0xa5, 0x92, 0x10, 0x04, 0x83, 0x60,
	0x8a, 0xf3, 0x19, 0xd4, 0x4a, 0x90, 0xf8, 0x04, 0x91, 0x0c, 0x87, 0x60, 0x92, 0x23, 0x1b, 0x0b,
	0x1b, 0x9f, 0x5d, 0xf2, 0xc7, 0xe2, 0xba, 0x1f, 0xbf, 0x99, 0xf9, 0x3e, 0x18, 0xd8, 0xbe, 0xe7,
	0x6f, 0x47, 0x21, 0xeb, 0x63, 0x8a, 0x39, 0xe2, 0xe8, 0xed, 0x67, 0x90, 0x0f, 0x30, 0xbf, 0xd9,
	0x44, 0x21, 0xaf, 0xb8, 0x83, 0xc1, 0x59, 0xc7, 0x99, 0x60, 0xea, 0xd2, 0x14, 0x2c, 0xc6, 0x47,
	0xcf, 0xcf, 0x9b, 0xf1, 0xd1, 0xcb, 0x5f, 0x98, 0x7b, 0x0a, 0x22, 0x8c, 0xc1, 0x7a, 0xea, 0xfb,
	0x95, 0xcb, 0x81, 0x3d, 0x50, 0x3d, 0xb8, 0x30, 0x05, 0xf1, 0x0e, 0xe6, 0x63, 0xcb, 0xe7, 0x83,
	0x60, 0xea, 0x6a, 0xbf, 0xd5, 0xa5, 0x57, 0xf7, 0x52, 0xf3, 0x3f, 0xc5, 0x5b, 0x98, 0x0e, 0x14,
	0x1c, 0x25, 0x3e, 0x0a, 0xa6, 0xae, 0xf7, 0x4b, 0xdb, 0x7b, 0xa9, 0xce, 0xf4, 0x99, 0xd4, 0xb0,
	0xe9, 0xfd, 0x2b, 0x4a, 0x58, 0x3a, 0x3f, 0x85, 0x9c, 0x7e, 0x38, 0x13, 0x83, 0x5a, 0xcc, 0x89,
	0xbb, 0xbf, 0x81, 0xa9, 0x25, 0x20, 0xc0, 0xf4, 0x4c, 0xde, 0x7e, 0xd1, 0xee, 0x0c, 0x37, 0x30,
	0xbe, 0x16, 0x62, 0x1f, 0x53, 0xfd, 0xc5, 0xe3, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc8, 0xf5,
	0x84, 0x71, 0x1c, 0x01, 0x00, 0x00,
}
